// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// bootstrap
arma::mat bootstrap(arma::mat thetaHat, arma::mat data, int numB);
RcppExport SEXP GraphKit_bootstrap(SEXP thetaHatSEXP, SEXP dataSEXP, SEXP numBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type thetaHat(thetaHatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type numB(numBSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap(thetaHat, data, numB));
    return rcpp_result_gen;
END_RCPP
}
// debias
arma::mat debias(arma::mat sigmaHat, arma::mat thetaHat);
RcppExport SEXP GraphKit_debias(SEXP sigmaHatSEXP, SEXP thetaHatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type sigmaHat(sigmaHatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type thetaHat(thetaHatSEXP);
    rcpp_result_gen = Rcpp::wrap(debias(sigmaHat, thetaHat));
    return rcpp_result_gen;
END_RCPP
}
// skipDownConn
bool skipDownConn(arma::mat deOmega, arma::mat bootStats, double alpha, int numConn);
RcppExport SEXP GraphKit_skipDownConn(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP, SEXP numConnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type numConn(numConnSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownConn(deOmega, bootStats, alpha, numConn));
    return rcpp_result_gen;
END_RCPP
}
// skipDownConnCI
arma::vec skipDownConnCI(arma::mat deOmega, arma::mat bootStats, double alpha);
RcppExport SEXP GraphKit_skipDownConnCI(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownConnCI(deOmega, bootStats, alpha));
    return rcpp_result_gen;
END_RCPP
}
// skipDownChain
bool skipDownChain(arma::mat deOmega, arma::mat bootStats, double alpha, int k);
RcppExport SEXP GraphKit_skipDownChain(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownChain(deOmega, bootStats, alpha, k));
    return rcpp_result_gen;
END_RCPP
}
// skipDownChainCI
arma::vec skipDownChainCI(arma::mat deOmega, arma::mat bootStats, double alpha);
RcppExport SEXP GraphKit_skipDownChainCI(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownChainCI(deOmega, bootStats, alpha));
    return rcpp_result_gen;
END_RCPP
}
// skipDownDeg
bool skipDownDeg(arma::mat deOmega, arma::mat bootStats, double alpha, int k);
RcppExport SEXP GraphKit_skipDownDeg(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownDeg(deOmega, bootStats, alpha, k));
    return rcpp_result_gen;
END_RCPP
}
// skipDownDegCI
arma::vec skipDownDegCI(arma::mat deOmega, arma::mat bootStats, double alpha);
RcppExport SEXP GraphKit_skipDownDegCI(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownDegCI(deOmega, bootStats, alpha));
    return rcpp_result_gen;
END_RCPP
}
// skipDownClique
bool skipDownClique(arma::mat deOmega, arma::mat bootStats, double alpha, int k);
RcppExport SEXP GraphKit_skipDownClique(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownClique(deOmega, bootStats, alpha, k));
    return rcpp_result_gen;
END_RCPP
}
// skipDownCliqueCI
arma::vec skipDownCliqueCI(arma::mat deOmega, arma::mat bootStats, double alpha);
RcppExport SEXP GraphKit_skipDownCliqueCI(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownCliqueCI(deOmega, bootStats, alpha));
    return rcpp_result_gen;
END_RCPP
}
// skipDownChrom
bool skipDownChrom(arma::mat deOmega, arma::mat bootStats, double alpha, int k);
RcppExport SEXP GraphKit_skipDownChrom(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownChrom(deOmega, bootStats, alpha, k));
    return rcpp_result_gen;
END_RCPP
}
// skipDownChromCI
arma::vec skipDownChromCI(arma::mat deOmega, arma::mat bootStats, double alpha);
RcppExport SEXP GraphKit_skipDownChromCI(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownChromCI(deOmega, bootStats, alpha));
    return rcpp_result_gen;
END_RCPP
}
// skipDownSingle
bool skipDownSingle(arma::mat deOmega, arma::mat bootStats, double alpha, int k);
RcppExport SEXP GraphKit_skipDownSingle(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownSingle(deOmega, bootStats, alpha, k));
    return rcpp_result_gen;
END_RCPP
}
// skipDownSingleCI
arma::vec skipDownSingleCI(arma::mat deOmega, arma::mat bootStats, double alpha);
RcppExport SEXP GraphKit_skipDownSingleCI(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownSingleCI(deOmega, bootStats, alpha));
    return rcpp_result_gen;
END_RCPP
}
// skipDownGirth
bool skipDownGirth(arma::mat deOmega, arma::mat bootStats, double alpha, int k);
RcppExport SEXP GraphKit_skipDownGirth(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownGirth(deOmega, bootStats, alpha, k));
    return rcpp_result_gen;
END_RCPP
}
// skipDownGirthCI
arma::vec skipDownGirthCI(arma::mat deOmega, arma::mat bootStats, double alpha);
RcppExport SEXP GraphKit_skipDownGirthCI(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownGirthCI(deOmega, bootStats, alpha));
    return rcpp_result_gen;
END_RCPP
}
// skipDownMatch
bool skipDownMatch(arma::mat deOmega, arma::mat bootStats, double alpha, int k);
RcppExport SEXP GraphKit_skipDownMatch(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownMatch(deOmega, bootStats, alpha, k));
    return rcpp_result_gen;
END_RCPP
}
// skipDownPlan
bool skipDownPlan(arma::mat deOmega, arma::mat bootStats, double alpha, int k);
RcppExport SEXP GraphKit_skipDownPlan(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownPlan(deOmega, bootStats, alpha, k));
    return rcpp_result_gen;
END_RCPP
}
// skipDownBipar
bool skipDownBipar(arma::mat deOmega, arma::mat bootStats, double alpha, int k);
RcppExport SEXP GraphKit_skipDownBipar(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownBipar(deOmega, bootStats, alpha, k));
    return rcpp_result_gen;
END_RCPP
}
// skipDownCycle
bool skipDownCycle(arma::mat deOmega, arma::mat bootStats, double alpha);
RcppExport SEXP GraphKit_skipDownCycle(SEXP deOmegaSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type deOmega(deOmegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(skipDownCycle(deOmega, bootStats, alpha));
    return rcpp_result_gen;
END_RCPP
}
// stepDown
arma::rowvec stepDown(arma::vec stats, arma::mat bootStats, double alpha);
RcppExport SEXP GraphKit_stepDown(SEXP statsSEXP, SEXP bootStatsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type stats(statsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type bootStats(bootStatsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(stepDown(stats, bootStats, alpha));
    return rcpp_result_gen;
END_RCPP
}
