# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bootstrap <- function(thetaHat, data, numB) {
    .Call('GraphKit_bootstrap', PACKAGE = 'GraphKit', thetaHat, data, numB)
}

debias <- function(sigmaHat, thetaHat) {
    .Call('GraphKit_debias', PACKAGE = 'GraphKit', sigmaHat, thetaHat)
}

skipDownConn <- function(deOmega, bootStats, alpha, numConn) {
    .Call('GraphKit_skipDownConn', PACKAGE = 'GraphKit', deOmega, bootStats, alpha, numConn)
}

skipDownConnCI <- function(deOmega, bootStats, alpha) {
    .Call('GraphKit_skipDownConnCI', PACKAGE = 'GraphKit', deOmega, bootStats, alpha)
}

skipDownChain <- function(deOmega, bootStats, alpha, k) {
    .Call('GraphKit_skipDownChain', PACKAGE = 'GraphKit', deOmega, bootStats, alpha, k)
}

skipDownChainCI <- function(deOmega, bootStats, alpha) {
    .Call('GraphKit_skipDownChainCI', PACKAGE = 'GraphKit', deOmega, bootStats, alpha)
}

skipDownDeg <- function(deOmega, bootStats, alpha, k) {
    .Call('GraphKit_skipDownDeg', PACKAGE = 'GraphKit', deOmega, bootStats, alpha, k)
}

skipDownDegCI <- function(deOmega, bootStats, alpha) {
    .Call('GraphKit_skipDownDegCI', PACKAGE = 'GraphKit', deOmega, bootStats, alpha)
}

skipDownClique <- function(deOmega, bootStats, alpha, k) {
    .Call('GraphKit_skipDownClique', PACKAGE = 'GraphKit', deOmega, bootStats, alpha, k)
}

skipDownCliqueCI <- function(deOmega, bootStats, alpha) {
    .Call('GraphKit_skipDownCliqueCI', PACKAGE = 'GraphKit', deOmega, bootStats, alpha)
}

skipDownChrom <- function(deOmega, bootStats, alpha, k) {
    .Call('GraphKit_skipDownChrom', PACKAGE = 'GraphKit', deOmega, bootStats, alpha, k)
}

skipDownChromCI <- function(deOmega, bootStats, alpha) {
    .Call('GraphKit_skipDownChromCI', PACKAGE = 'GraphKit', deOmega, bootStats, alpha)
}

skipDownSingle <- function(deOmega, bootStats, alpha, k) {
    .Call('GraphKit_skipDownSingle', PACKAGE = 'GraphKit', deOmega, bootStats, alpha, k)
}

skipDownSingleCI <- function(deOmega, bootStats, alpha) {
    .Call('GraphKit_skipDownSingleCI', PACKAGE = 'GraphKit', deOmega, bootStats, alpha)
}

skipDownGirth <- function(deOmega, bootStats, alpha, k) {
    .Call('GraphKit_skipDownGirth', PACKAGE = 'GraphKit', deOmega, bootStats, alpha, k)
}

skipDownGirthCI <- function(deOmega, bootStats, alpha) {
    .Call('GraphKit_skipDownGirthCI', PACKAGE = 'GraphKit', deOmega, bootStats, alpha)
}

skipDownMatch <- function(deOmega, bootStats, alpha, k) {
    .Call('GraphKit_skipDownMatch', PACKAGE = 'GraphKit', deOmega, bootStats, alpha, k)
}

skipDownPlan <- function(deOmega, bootStats, alpha, k) {
    .Call('GraphKit_skipDownPlan', PACKAGE = 'GraphKit', deOmega, bootStats, alpha, k)
}

skipDownBipar <- function(deOmega, bootStats, alpha, k) {
    .Call('GraphKit_skipDownBipar', PACKAGE = 'GraphKit', deOmega, bootStats, alpha, k)
}

skipDownCycle <- function(deOmega, bootStats, alpha) {
    .Call('GraphKit_skipDownCycle', PACKAGE = 'GraphKit', deOmega, bootStats, alpha)
}

stepDown <- function(stats, bootStats, alpha) {
    .Call('GraphKit_stepDown', PACKAGE = 'GraphKit', stats, bootStats, alpha)
}

